print("Today's date?:")
date = input()
print("What is your favorite number?")
number = input()
print("What is your favorite color?")
color = input()
print("How many countries have you visited?")
countries = input()
print("Pick a number between 1 and 100?:")
first_number = int(input())
print("Pick a number between 1 and 100?:")
second_number = int(input())
sum = first_number + second_number
print("Sum: " + str(sum))